Do not hardcode the number and positions of the divertor starting points.  Read them instead from the file div_start.dat. Its role changes thus from output to input. Copy the file div_start.dat to the working directory in the substrikes_simple script and complain if it does not exist.
git-svn-id: https://scm.gforge.inria.fr/svn/aster/jorek2/trunk@1029 d232b540-7924-0410-b3cd-8064bb5aaf68

diff --git a/run_jorek/substrikes_simple b/run_jorek/substrikes_simple
--- a/run_jorek/substrikes_simple
+++ b/run_jorek/substrikes_simple
@@ -444,6 +444,17 @@ else
     echo " using old namelist file connecvtk.nml "
 fi
 
+if [ ! -e ${RESDIR}/div_start.dat ]; then
+    if [ ! -e ${WKDIR}/div_start.dat ]; then
+	echo " ERROR: input file div_start.dat does not exist, exiting ";
+	exit 1
+    else
+	cp ${WKDIR}/div_start.dat ${RESDIR}/
+    fi
+else
+    echo " using old input file div_start.dat "
+fi
+
 # Execution control
 # -----------------
 echo " ============> writing output in file    = " ${CASE}/${STRIKEXECNAMEOUT}.out
